const blacklistRegexes: RegExp[] = [
  /@lwc\/lwc\/no-unexpected-wire-adapter-usages/,
  /@lwc\/lwc\/no-unknown-wire-adapters/,
  /@lwc\/lwc\/no-restricted-browser-globals-during-ssr/,
  /@lwc\/lwc\/no-node-env-in-ssr/,
  /@typescript-eslint\/consistent-type-imports/,
  /@typescript-eslint\/ban-types/,
  /@typescript-eslint\/await-thenable/,
  /@typescript-eslint\/consistent-return/,
  /@typescript-eslint\/dot-notation/,
  /@typescript-eslint\/no-array-delete/,
  /@typescript-eslint\/consistent-type-exports/,
  /@typescript-eslint\/no-floating-promises/,
  /@typescript-eslint\/no-duplicate-type-constituents/,
  /@typescript-eslint\/no-base-to-string/,
  /@typescript-eslint\/no-deprecated/,
  /@typescript-eslint\/no-misused-promises/,
  /@typescript-eslint\/no-implied-eval/,
  /@typescript-eslint\/no-mixed-enums/,
  /@typescript-eslint\/no-unnecessary-condition/,
  /@typescript-eslint\/no-unsafe-return/,
  /@typescript-eslint\/prefer-destructuring/,
  /@typescript-eslint\/no-unnecessary-type-parameters/,
  /@typescript-eslint\/non-nullable-type-assertion-style/,
  /@typescript-eslint\/no-unsafe-argument/,
  /@typescript-eslint\/only-throw-error/,
  /@typescript-eslint\/no-unsafe-call/,
  /@typescript-eslint\/prefer-optional-chain/,
  /@typescript-eslint\/prefer-regexp-exec/,
  /@typescript-eslint\/prefer-return-this-type/,
  /@typescript-eslint\/prefer-string-starts-ends-with/,
  /@typescript-eslint\/promise-function-async/,
  /@typescript-eslint\/require-array-sort-compare/,
  /@typescript-eslint\/require-await/,
  /@typescript-eslint\/restrict-plus-operands/,
  /@typescript-eslint\/restrict-template-expressions/,
  /@typescript-eslint\/return-await/,
  /@typescript-eslint\/strict-boolean-expressions/,
  /@typescript-eslint\/switch-exhaustiveness-check/,
  /@typescript-eslint\/unbound-method/,
  /@typescript-eslint\/use-unknown-in-catch-callback-variable/,
  /@typescript-eslint\/prefer-reduce-type-parameter/,
  /@typescript-eslint\/prefer-readonly-parameter-types/,
  /@typescript-eslint\/prefer-promise-reject-errors/,
  /@typescript-eslint\/prefer-readonly/,
  /@typescript-eslint\/no-unsafe-member-access/,
  /@typescript-eslint\/prefer-find/,
  /@typescript-eslint\/prefer-includes/,
  /@typescript-eslint\/prefer-nullish-coalescing/,
  /@typescript-eslint\/no-unsafe-enum-comparison/,
  /@typescript-eslint\/no-unsafe-assignment/,
  /@typescript-eslint\/no-unnecessary-qualifier/,
  /@typescript-eslint\/no-unnecessary-type-arguments/,
  /@typescript-eslint\/no-unnecessary-type-assertion/,
  /@typescript-eslint\/no-unnecessary-template-expression/,
  /@typescript-eslint\/no-meaningless-void-operator/,
  /@typescript-eslint\/no-unnecessary-boolean-literal-compare/,
  /@typescript-eslint\/no-redundant-type-constituents/,
  /angular\/service-name/,
  /ember\/no-restricted-property-modifications/,
  /ember\/template-indent/,
  /backbone\/event-scope/,
  /backbone\/no-silent/,
  /filenames\/match-regex/,
  /filenames\/match-exported/,
  /filenames\/no-index/,
  /functional\/functional-parameters/,
  /functional\/immutable-data/,
  /functional\/no-conditional-statements/,
  /functional\/no-expression-statements/,
  /functional\/no-let/,
  /functional\/no-mixed-types/,
  /functional\/no-return-void/,
  /functional\/no-throw-statements/,
  /functional\/no-try-statements/,
  /functional\/prefer-immutable-types/,
  /functional\/type-declaration-immutability/,
  /import\/newline-after-import/,
  /xss\/no-mixed-html/,
  /unused-imports\/.*-ts/,
  /yml\/sort-sequence-values/
]

const documentationBlacklistRegexes: RegExp[] = [
  /@shopify\/no-debugger/,
  /react-redux\/mapStateToProps-prefer-parameters-names/,
  /react-redux\/prefer-separate-component-file/,
  /react-redux\/mapStateToProps-prefer-hoisted/,
  /react-redux\/connect-prefer-named-arguments/,
  /react-redux\/mapDispatchToProps-prefer-parameters-names/,
  /react-redux\/mapDispatchToProps-returns-object/,
  /react-redux\/mapDispatchToProps-prefer-shorthand/,
  /react-redux\/connect-prefer-minimum-two-arguments/,
  /react-redux\/mapStateToProps-no-store/,
  /jasmine\/named-spy/,
  /jasmine\/no-unsafe-spy/,
  /jasmine\/no-focused-tests/,
  /jasmine\/no-assign-spyon/,
  /jasmine\/no-describe-variables/,
  /jasmine\/expect-matcher/,
  /jasmine\/no-pending-tests/,
  /jasmine\/no-suite-callback-args/,
  /jasmine\/prefer-toHaveBeenCalledWith/,
  /jasmine\/no-disabled-tests/,
  /jasmine\/prefer-jasmine-matcher/,
  /jasmine\/no-global-setup/,
  /jasmine\/expect-single-argument/,
  /jasmine\/valid-expect/
]

function testRegex (regexes: RegExp[], value: string): boolean {
  return regexes.some((regex) => regex.test(value))
}

export function isBlacklisted (ruleId: string): boolean {
  return testRegex(blacklistRegexes, ruleId)
}

// Removes a pattern from the documentation
// but still supports it with eslint config file
export function isBlacklistedOnlyFromDocumentation (ruleId: string): boolean {
  return testRegex(documentationBlacklistRegexes, ruleId)
}
